services:
  db-peliculas:
    image: postgres:16
    container_name: db-peliculas
    restart: always
    environment:
      POSTGRES_DB: peliculas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - peliculas_data:/var/lib/postgresql/data

  ms-peliculas:
    build:
      context: ./ms-peliculas
    container_name: ms-peliculas
    restart: always
    depends_on:
      - db-peliculas
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-peliculas:5432/peliculas_db
    ports:
      - "8001:8000"

  db-funciones:
    image: postgres:16
    container_name: db-funciones
    restart: always
    environment:
      POSTGRES_DB: funciones_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - funciones_data:/var/lib/postgresql/data

  ms-funciones:
    build:
      context: ./ms-funciones
    container_name: ms-funciones
    restart: always
    depends_on:
      - db-funciones
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-funciones:5432/funciones_db
    ports:
      - "8002:8000"

  db-reservas:
    image: postgres:16
    container_name: db-reservas
    restart: always
    environment:
      POSTGRES_DB: reservas_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - reservas_data:/var/lib/postgresql/data

  ms-reservas-asientos:
    build:
      context: ./ms-reservas-asientos
    container_name: ms-reservas-asientos
    restart: always
    depends_on:
      - db-reservas
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-reservas:5432/reservas_db
    ports:
      - "8003:8000"

  db-compras:
    image: postgres:16
    container_name: db-compras
    restart: always
    environment:
      POSTGRES_DB: compras_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - compras_data:/var/lib/postgresql/data

  ms-compras-boletos:
    build:
      context: ./ms-compras-boletos
    container_name: ms-compras-boletos
    restart: always
    depends_on:
      - db-compras
      - ms-reservas-asientos
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db-compras:5432/compras_db
      RESERVAS_API_URL: http://ms-reservas-asientos:8000/api/v1
    ports:
      - "8004:8000"

volumes:
  peliculas_data:
  funciones_data:
  reservas_data:
  compras_data:
